services:
  DotnetstoreLandlord:
    image: ${DOCKER_REGISTRY:-}dotnetstorelandlord
    container_name: landlord.webapi
    build:
      context: ./src/WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - Dotnetstore.Landlord-Database
  
  Dotnetstore.Landlord-Database:
    image: postgres:latest
    container_name: landlord.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DotnetstoreLandlord
    volumes:
      - ./.container/landlord-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"